import numpy as np
from magtense.micromag import MicromagProblem
from typing import Optional

from .load_matlab_struct import load_matlab_struct
from .rand_spherical_cap import rand_spherical_cap

def setup_grain_problem_from_matfile(
                    fname : str,                                # matlab file name
                    cuda : bool = False,                        # use cuda or not
                    cvode : bool = False,                       # use cvode or not
                    t_end : float = 40e-9,                      # end time for each hysteresis step
                    nt : int = 2,                               # number of time steps for each hysteresis step
                    Hyst_dir : np.ndarray = np.array([0,0,1]),  # hysteresis direction
                    rng: Optional[np.random.Generator] = None,  #
                    exch_val: list | np.ndarray | None = None,
                    exch_rows: list | np.ndarray | None = None,
                    exch_col: list | np.ndarray | None = None,
                    exch_nval: int = 1,
                    exch_nrow: int = 1,
                    exch_ncols: int = 1,
                    passexch : int = 0
                    ) -> MicromagProblem:
    

    #---------------- Load mesh from matlab struct ----------------
    # NOTE - expects matlab file generated by "Grain_generator.m" - for newer versions it may fail as these are saved with h5py
    mesh_cart, GridInfo, mesh_params, iIn = load_matlab_struct(fname)
    #---------------------------------------------------------------
    #---------------- Setup problem parameters ----------------
    grid_type = "unstructuredPrisms"
    N_grains = mesh_params["nGrains"][0][0]
    mu0 = 4 * np.pi * 1e-7
    alpha = 4000.0
    gamma = 0.0
        #----------- inside grains -----------
    Ms = 1.61/mu0 ; # 1.61 T
    K0 = 4.3e6 ;    # J/m3
    A0 = 7.7e-12 ;  # J/m3
        #------------------------------------

        #-------- intergrain (ig) -----------
    A0igFactor = 1.0                                            # Exchange stiffness factor 
    Msig = 0.5/mu0                                              # Saturation magnetization  
        #------------------------------------
        #----------- setting grain directions -----------
    cone_angle_degree = 1.0
    if rng is None:
        rng = np.random.default_rng()


    mag_dir = rand_spherical_cap(cone_angle_degree, N=N_grains, cone_dir=Hyst_dir, rng=rng)
        #--------------------------------------------
    #----------------------------------------------------------------------


    grid_pts = mesh_cart["pos_out"]
    grid_abc = mesh_cart["dims_out"]

    N_cell = grid_pts.shape[0]
    grid_L = mesh_params["thisGridL"][0]
    res = mesh_params["resolution"][0]


    #----------------- Initialize MicromagProblem -----------------
    problem = MicromagProblem(
        res=res,
        grid_L=grid_L,
        alpha=alpha,
        gamma=gamma,
        grid_pts=grid_pts,
        grid_abc=grid_abc,
        grid_type=grid_type,
        cuda=cuda,
        cvode=cvode,
        exch_val=exch_val,
        exch_rows=exch_rows,
        exch_col=exch_col,
        exch_nval=exch_nval,
        exch_nrow=exch_nrow,
        exch_ncols=exch_ncols,
        passexch=passexch
    )
    #-------------------------------------------------------------


    #---------- set easy axis per grain ---------------
    # NOTE - u_ea set to zero by default, so no need to initilize it here or set intergrain values
    for grain_idx in range(1, N_grains + 1):
        cell_idx = mesh_cart["GrainIndex"].T[0].astype(np.int32) == grain_idx
        problem.u_ea[cell_idx, :] = mag_dir[grain_idx - 1]
    #---------------------------------------------------

    #------------- set solver to explicit to make hysteresis -------------
    #            makes solver use "last" magnetization as initial state for next step
    problem.solver = "explicit"
    #---------------------------------------------------------------------

    #----------------- initial magnetization along  hysteresis dir -----------------
    problem.m0[:,:] = Hyst_dir[np.newaxis,:]      
    #-----------------------------------------------------------------      

    problem.Ms = Ms * np.ones((N_cell, 1)) 
    problem.K0 = K0 * np.ones((N_cell, 1))
    problem.A0 = A0 * np.ones((N_cell, 1))


    #---------- intergrain (ig) indices ----------------
    ig_idx = mesh_cart["GrainIndex"].T[0].astype(np.int32) == N_grains + 1
    problem.Ms[ig_idx] = Msig
    problem.A0[ig_idx] = A0 * A0igFactor
    #---------------------------------------------------


    #-------------- set time array --------------
    # NOTE - just two points... Used for each step?
    t = np.linspace(0, t_end, nt)
    problem.t = t
    problem.nt = len(t)
    #---------------------------------------------
    #-------------- set convergence time array --------------
    t_conv = np.linspace(0, t_end, nt)
    problem.t_conv = t_conv
    problem.nt_conv = len(t_conv)
    #---------------------------------------------


    problem.usereturnhall = True


    return problem