    
clear all

debug = false;

if debug
    mex -g -LMagStatPrisms2\MagStatVersion2\MagStatVersion2\x64\debug\ -lMagStatVersion2...
    -IMagStatPrisms2\MagStatVersion2\MagStatVersion2\x64\debug\ ...
    -LSpecialFunctions\SpecialFunctions\x64\release\ -lSpecialFunctions ...
    -ISpecialFunctions\SpecialFunctions\x64\release\ ...
    -LNumericalIntegrationLib\NumericalIntegration\NumericalIntegration\x64\release\ -lNumericalIntegration ...
    -INumericalIntegrationLib\NumericalIntegration\NumericalIntegration\x64\release\ ...
    -LTileDemagTensor\TileDemagTensor\TileDemagTensor\x64\debug\ -lTileDemagTensor ...
    -ITileDemagTensor\TileDemagTensor\TileDemagTensor\x64\debug\ ...    
    MagStatPrismMex\MagStatPrismMex\iterateMagnetization_mex.f90 COMPFLAGS="$COMPFLAGS /O2 /Qopenmp /extend_source:132 /real_size:64 "
        
mex -g -LMagStatPrisms2\MagStatVersion2\MagStatVersion2\x64\debug\ -lMagStatVersion2...
    -IMagStatPrisms2\MagStatVersion2\MagStatVersion2\x64\debug\ ...
    -LSpecialFunctions\SpecialFunctions\x64\release\ -lSpecialFunctions ...
    -ISpecialFunctions\SpecialFunctions\x64\release\ ...
    -LNumericalIntegrationLib\NumericalIntegration\NumericalIntegration\x64\release\ -lNumericalIntegration ...
    -INumericalIntegrationLib\NumericalIntegration\NumericalIntegration\x64\release\ ...
    -LTileDemagTensor\TileDemagTensor\TileDemagTensor\x64\debug\ -lTileDemagTensor ...
    -ITileDemagTensor\TileDemagTensor\TileDemagTensor\x64\debug\ ...    
    MagStatPrismMex\MagStatPrismMex\getHFromTiles_mex.f90 COMPFLAGS="$COMPFLAGS /O2 /Qopenmp /extend_source:132 /real_size:64 "

mex -g -LMagStatPrisms2\MagStatVersion2\MagStatVersion2\x64\debug\ -lMagStatVersion2...
    -IMagStatPrisms2\MagStatVersion2\MagStatVersion2\x64\debug\ ...
    -LSpecialFunctions\SpecialFunctions\x64\release\ -lSpecialFunctions ...
    -ISpecialFunctions\SpecialFunctions\x64\release\ ...
    -LNumericalIntegrationLib\NumericalIntegration\NumericalIntegration\x64\release\ -lNumericalIntegration ...
    -INumericalIntegrationLib\NumericalIntegration\NumericalIntegration\x64\release\ ...
    -LTileDemagTensor\TileDemagTensor\TileDemagTensor\x64\debug\ -lTileDemagTensor ...
    -ITileDemagTensor\TileDemagTensor\TileDemagTensor\x64\debug\ ...    
    MagStatPrismMex\MagStatPrismMex\getNFromCylTile_mex.f90 COMPFLAGS="$COMPFLAGS /O2 /Qopenmp /extend_source:132 /real_size:64 "

mex -g -LMagneticForceIntegrator\MagneticForceIntegrator\x64\debug\ -lMagneticForceIntegrator...
    -IMagneticForceIntegrator\MagneticForceIntegrator\x64\debug\ ...
    -LMagStatPrisms2\MagStatVersion2\MagStatVersion2\x64\release\ -lMagStatVersion2...    
    -IMagStatPrisms2\MagStatVersion2\MagStatVersion2\x64\release\ ...
    -LNumericalRecipes\NumericalRecipes\x64\debug\ -lNumericalRecipes...    
    -INumericalRecipes\NumericalRecipes\x64\debug\ ...
    -LSpecialFunctions\SpecialFunctions\x64\release\ -lSpecialFunctions ...
    -ISpecialFunctions\SpecialFunctions\x64\release\ ...
    -LNumericalIntegrationLib\NumericalIntegration\NumericalIntegration\x64\debug\ -lNumericalIntegration ...
    -INumericalIntegrationLib\NumericalIntegration\NumericalIntegration\x64\debug\ ...
    -LTileDemagTensor\TileDemagTensor\TileDemagTensor\x64\release\ -lTileDemagTensor ...
    -ITileDemagTensor\TileDemagTensor\TileDemagTensor\x64\release\ ...    
    MagStatPrismMex\MagStatPrismMex\getMagForce_mex.f90 COMPFLAGS="$COMPFLAGS /O2 /Qopenmp /extend_source:132 /real_size:64 "
        
else
    
mex -g -LMagStatPrisms2\MagStatVersion2\MagStatVersion2\x64\release\ -lMagStatVersion2...
    -IMagStatPrisms2\MagStatVersion2\MagStatVersion2\x64\release\ ...
    -LSpecialFunctions\SpecialFunctions\x64\release\ -lSpecialFunctions ...
    -ISpecialFunctions\SpecialFunctions\x64\release\ ...
    -LNumericalIntegrationLib\NumericalIntegration\NumericalIntegration\x64\release\ -lNumericalIntegration ...
    -INumericalIntegrationLib\NumericalIntegration\NumericalIntegration\x64\release\ ...
    -LTileDemagTensor\TileDemagTensor\TileDemagTensor\x64\release\ -lTileDemagTensor ...
    -ITileDemagTensor\TileDemagTensor\TileDemagTensor\x64\release\ ...    
    MagStatPrismMex\MagStatPrismMex\IterateMagnetization_mex.f90 COMPFLAGS="$COMPFLAGS /O2 /Qopenmp /extend_source:132 /real_size:64 "
        
mex -g -LMagStatPrisms2\MagStatVersion2\MagStatVersion2\x64\release\ -lMagStatVersion2...
    -IMagStatPrisms2\MagStatVersion2\MagStatVersion2\x64\release\ ...
    -LSpecialFunctions\SpecialFunctions\x64\release\ -lSpecialFunctions ...
    -ISpecialFunctions\SpecialFunctions\x64\release\ ...
    -LNumericalIntegrationLib\NumericalIntegration\NumericalIntegration\x64\release\ -lNumericalIntegration ...
    -INumericalIntegrationLib\NumericalIntegration\NumericalIntegration\x64\release\ ...
    -LTileDemagTensor\TileDemagTensor\TileDemagTensor\x64\release\ -lTileDemagTensor ...
    -ITileDemagTensor\TileDemagTensor\TileDemagTensor\x64\release\ ...    
    MagStatPrismMex\MagStatPrismMex\getHFromTiles_mex.f90 COMPFLAGS="$COMPFLAGS /O2 /Qopenmp /extend_source:132 /real_size:64 "

mex -g -LMagStatPrisms2\MagStatVersion2\MagStatVersion2\x64\release\ -lMagStatVersion2...
    -IMagStatPrisms2\MagStatVersion2\MagStatVersion2\x64\release\ ...
    -LSpecialFunctions\SpecialFunctions\x64\release\ -lSpecialFunctions ...
    -ISpecialFunctions\SpecialFunctions\x64\release\ ...
    -LNumericalIntegrationLib\NumericalIntegration\NumericalIntegration\x64\release\ -lNumericalIntegration ...
    -INumericalIntegrationLib\NumericalIntegration\NumericalIntegration\x64\release\ ...
    -LTileDemagTensor\TileDemagTensor\TileDemagTensor\x64\release\ -lTileDemagTensor ...
    -ITileDemagTensor\TileDemagTensor\TileDemagTensor\x64\release\ ...    
    MagStatPrismMex\MagStatPrismMex\getNFromCylTile_mex.f90 COMPFLAGS="$COMPFLAGS /O2 /Qopenmp /extend_source:132 /real_size:64 "


mex -g -LMagneticForceIntegrator\MagneticForceIntegrator\x64\release\ -lMagneticForceIntegrator...
    -IMagneticForceIntegrator\MagneticForceIntegrator\x64\release\ ...
    -LMagStatPrisms2\MagStatVersion2\MagStatVersion2\x64\release\ -lMagStatVersion2...
    -IMagStatPrisms2\MagStatVersion2\MagStatVersion2\x64\release\ ...
    -LNumericalRecipes\NumericalRecipes\x64\release\ -lNumericalRecipes...    
    -INumericalRecipes\NumericalRecipes\x64\release\ ...
    -LSpecialFunctions\SpecialFunctions\x64\release\ -lSpecialFunctions ...
    -ISpecialFunctions\SpecialFunctions\x64\release\ ...
    -LNumericalIntegrationLib\NumericalIntegration\NumericalIntegration\x64\release\ -lNumericalIntegration ...
    -INumericalIntegrationLib\NumericalIntegration\NumericalIntegration\x64\release\ ...
    -LTileDemagTensor\TileDemagTensor\TileDemagTensor\x64\release\ -lTileDemagTensor ...
    -ITileDemagTensor\TileDemagTensor\TileDemagTensor\x64\release\ ...    
    MagStatPrismMex\MagStatPrismMex\getMagForce_mex.f90 COMPFLAGS="$COMPFLAGS /O2 /Qopenmp /extend_source:132 /real_size:64 "
        
end