clear all
% mex -g -LMagStatPrismLib\MagStatPrismLib\x64\Release\ -lMagStatPrismLib ...
mex -LMagStatPrismLib\MagStatPrismLib\x64\release\ -lMagStatPrismLib ...
    -IMagStatPrismLib\MagStatPrismLib\x64\release\ ...
    MagStatPrismMEX\MagStatPrismMEX\magStatMEX.f90 ...   
    COMPFLAGS="$COMPFLAGS  /Qopenmp /extend_source:132 /real_size:64 "