clearvars
    
mex -g -Lsource\DemagField\DemagField\x64\release\ -lDemagField...
       -Isource\DemagField\DemagField\x64\release\ ...
       -Lsource\NumericalIntegration\NumericalIntegration\x64\release\ -lNumericalIntegration ...
       -Isource\NumericalIntegration\NumericalIntegration\x64\release\ ...
       -Lsource\TileDemagTensor\TileDemagTensor\x64\release\ -lTileDemagTensor ...
       -Isource\TileDemagTensor\TileDemagTensor\x64\release\ ...        
    source\MagTenseMEX\MagTenseMEX\IterateMagnetization_mex.f90 COMPFLAGS="$COMPFLAGS /O3 /extend_source:132 /real_size:64 /fpe:0"

movefile IterateMagnetization_mex.mexw64 matlab\MEX_files\IterateMagnetization_mex.mexw64
movefile IterateMagnetization_mex.mexw64.pdb matlab\MEX_files\IterateMagnetization_mex.mexw64.pdb
        
mex -g -Lsource\DemagField\DemagField\x64\release\ -lDemagField...
       -Isource\DemagField\DemagField\x64\release\ ...
       -Lsource\NumericalIntegration\NumericalIntegration\x64\release\ -lNumericalIntegration ...
       -Isource\NumericalIntegration\NumericalIntegration\x64\release\ ...
       -Lsource\TileDemagTensor\TileDemagTensor\x64\release\ -lTileDemagTensor ...
       -Isource\TileDemagTensor\TileDemagTensor\x64\release\ ...    
    source\MagTenseMEX\MagTenseMEX\getHFromTiles_mex.f90 COMPFLAGS="$COMPFLAGS /O3 /extend_source:132 /real_size:64  /fpe:0"

movefile getHFromTiles_mex.mexw64 matlab\MEX_files\getHFromTiles_mex.mexw64
movefile getHFromTiles_mex.mexw64.pdb matlab\MEX_files\getHFromTiles_mex.mexw64.pdb

mex -g -Lsource\DemagField\DemagField\x64\release\ -lDemagField...
       -Isource\DemagField\DemagField\x64\release\ ...
       -Lsource\NumericalIntegration\NumericalIntegration\x64\release\ -lNumericalIntegration ...
       -Isource\NumericalIntegration\NumericalIntegration\x64\release\ ...
       -Lsource\TileDemagTensor\TileDemagTensor\x64\release\ -lTileDemagTensor ...
       -Isource\TileDemagTensor\TileDemagTensor\x64\release\ ...        
    source\MagTenseMEX\MagTenseMEX\getNFromTile_mex.f90 COMPFLAGS="$COMPFLAGS /O3 /extend_source:132 /real_size:64  /fpe:0"

movefile getNFromTile_mex.mexw64 matlab\MEX_files\getNFromTile_mex.mexw64
movefile getNFromTile_mex.mexw64.pdb matlab\MEX_files\getNFromTile_mex.mexw64.pdb

mex -g -Lsource\MagneticForceIntegrator\MagneticForceIntegrator\x64\release\ -lMagneticForceIntegrator...
       -Isource\MagneticForceIntegrator\MagneticForceIntegrator\x64\release\ ...
       -Lsource\DemagField\DemagField\x64\release\ -lDemagField...
       -Isource\DemagField\DemagField\x64\release\ ...
       -Lsource\NumericalIntegration\NumericalIntegration\x64\release\ -lNumericalIntegration ...
       -Isource\NumericalIntegration\NumericalIntegration\x64\release\ ...
       -Lsource\TileDemagTensor\TileDemagTensor\x64\release\ -lTileDemagTensor ...
       -Isource\TileDemagTensor\TileDemagTensor\x64\release\ ...        
    source\MagTenseMEX\MagTenseMEX\getMagForce_mex.f90 COMPFLAGS="$COMPFLAGS /O2 /Qopenmp /extend_source:132 /real_size:64  /fpe:0"
        
movefile getMagForce_mex.mexw64 matlab\MEX_files\getMagForce_mex.mexw64
movefile getMagForce_mex.mexw64.pdb matlab\MEX_files\getMagForce_mex.mexw64.pdb
