
clear all
%COMPFLAGS5="$COMPFLAGS /MT /Qopenmp /extend_source:132 /real_size:64" ...
mex  -g -LSpecialFunctions\SpecialFunctions\x64\release\ -lSpecialFunctions ...
    -ISpecialFunctions\SpecialFunctions\x64\release\ ...
    MagStatPrismMex\MagStatPrismMex\EllipticIncomplete_mex.f90 COMPFLAGS="$COMPFLAGS  /Qopenmp /extend_source:132 /real_size:64 "
    