
clear all
%COMPFLAGS5="$COMPFLAGS /MT /Qopenmp /extend_source:132 /real_size:64" ...
mex  -LSpecialFunctions\SpecialFunctions\x64\release\ -lSpecialFunctions ...
    -ISpecialFunctions\SpecialFunctions\x64\release\ ...
    -LNumericalIntegrationLib\NumericalIntegration\NumericalIntegration\x64\release\ -lNumericalIntegration ...
    -INumericalIntegrationLib\NumericalIntegration\NumericalIntegration\x64\release\ ...
    -LTileDemagTensor\TileDemagTensor\TileDemagTensor\x64\release\ -lTileDemagTensor ...
    -ITileDemagTensor\TileDemagTensor\TileDemagTensor\x64\release\ ...
    MagStatPrismMex\MagStatPrismMex\N_cyl_piece_mex.f90 COMPFLAGS="$COMPFLAGS /O2 /Qopenmp /extend_source:132 /real_size:64 "
        