clear all
mex  COMPFLAGS5="$COMPFLAGS /MT /Qopenmp /extend_source:132 /real_size:64" ...
    -LNumericalIntegrationLib\NumericalIntegration\NumericalIntegration\x64\release\ -lNumericalIntegration ...
    -INumericalIntegrationLib\NumericalIntegration\NumericalIntegration\x64\release\ ...
    -LMagStatPrismLib\MagStatPrismLib\x64\Release\ -lMagStatPrismLib ...
    -IMagStatPrismLib\MagStatPrismLib\x64\Release\ ...
    MagStatPrismMEX\MagStatPrismMEX\integral2_mex.f90
    