
clear all

mex -g -LMagneticForceIntegrator\MagneticForceIntegrator\x64\release\ -lMagneticForceIntegrator...
    -IMagneticForceIntegrator\MagneticForceIntegrator\x64\release\ ...
    -LMagStatPrisms2\MagStatVersion2\MagStatVersion2\x64\release\ -lMagStatVersion2...
    -IMagStatPrisms2\MagStatVersion2\MagStatVersion2\x64\release\ ...
    -LSpecialFunctions\SpecialFunctions\x64\release\ -lSpecialFunctions ...
    -ISpecialFunctions\SpecialFunctions\x64\release\ ...
    -LNumericalIntegrationLib\NumericalIntegration\NumericalIntegration\x64\release\ -lNumericalIntegration ...
    -INumericalIntegrationLib\NumericalIntegration\NumericalIntegration\x64\release\ ...
    -LTileDemagTensor\TileDemagTensor\TileDemagTensor\x64\release\ -lTileDemagTensor ...
    -ITileDemagTensor\TileDemagTensor\TileDemagTensor\x64\release\ ...    
    MagStatPrismMex\MagStatPrismMex\getMagForce_mex.f90 COMPFLAGS="$COMPFLAGS /O2 /Qopenmp /extend_source:132 /real_size:64 "
        