clear all
% mex -g -LMagStatPrismLib\MagStatPrismLib\x64\Release\ -lMagStatPrismLib ...
mex -g -LMagStatPrismLib\MagStatPrismLib\x64\Debug\ -lMagStatPrismLib ...
    -IMagStatPrismLib\MagStatPrismLib\x64\Debug\ ...
    MagStatPrismMEX\MagStatPrismMEX\magStatMEX.f90 ...
    COMPFLAGS5="$COMPFLAGS /MT /extend_source:132 /real_size:64"