%use clear all as this also clears dependencies to the .mex files and thus
%they can be overwritten
clear all
    
mex -g -Lsource\NumericalIntegration\NumericalIntegration\x64\Release\ -lNumericalIntegration ...
       -Isource\NumericalIntegration\NumericalIntegration\x64\Release\ ...   
       -Lsource\DemagField\DemagField\x64\Release\ -lDemagField...
       -Isource\DemagField\DemagField\x64\Release\ ...
       -Lsource\TileDemagTensor\TileDemagTensor\x64\Release\ -lTileDemagTensor ...
       -Isource\TileDemagTensor\TileDemagTensor\x64\Release\ ...    
       -Lsource\MagTenseFortranCuda\x64\Release\ -lMagTenseFortranCuda ...
       -Isource\MagTenseFortranCuda\x64\Release\ ...   
       '-Lc:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\lib\x64\' -lcublas ...
       '-Lc:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\lib\x64\' -lcudart_static ...
       '-Lc:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2019\windows\mkl\lib\intel64_win\' -lmkl_intel_lp64 ...       
       '-Ic:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2019\windows\mkl\include\' ...
       '-LC:\Users\emib\Downloads\sundials_4_1\Automated_test_inst_dir\lib' -lsundials_nvecserial ...
       '-LC:\Users\emib\Downloads\sundials_4_1\Automated_test_inst_dir\lib' -lsundials_sunmatrixdense ...
       '-LC:\Users\emib\Downloads\sundials_4_1\Automated_test_inst_dir\lib' -lsundials_sunlinsoldense ...
       '-LC:\Users\emib\Downloads\sundials_4_1\Automated_test_inst_dir\lib' -lsundials_fnvecserial_mod ...
       '-LC:\Users\emib\Downloads\sundials_4_1\Automated_test_inst_dir\lib' -lsundials_cvode ...
       '-LC:\Users\emib\Downloads\sundials_4_1\Automated_test_inst_dir\lib' -lsundials_fsunnonlinsolfixedpoint_mod ... ...       
       '-IC:\Users\emib\Downloads\sundials_4_1\Automated_test_inst_dir\include' ...       
       -Lsource\MagTenseMicroMag\x64\Release\ -lMagTenseMicroMag ...
       -Isource\MagTenseMicroMag\x64\Release\ ...
       source\MagTenseMEX\MagTenseMEX\MagTenseLandauLifshitzSolver_mex.f90 COMPFLAGS="$COMPFLAGS /O3 /extend_source:132 /real_size:64 /fpe:0" -R2018a

movefile MagTenseLandauLifshitzSolver_mex.mexw64 matlab\MEX_files\MagTenseLandauLifshitzSolver_mex.mexw64
movefile MagTenseLandauLifshitzSolver_mex.mexw64.pdb matlab\MEX_files\MagTenseLandauLifshitzSolver_mex.mexw64.pdb

mex -g -Lsource\DemagField\DemagField\x64\Release\ -lDemagField...
       -Isource\DemagField\DemagField\x64\Release\ ...
       -Lsource\NumericalIntegration\NumericalIntegration\x64\Release\ -lNumericalIntegration ...
       -Isource\NumericalIntegration\NumericalIntegration\x64\Release\ ...
       -Lsource\TileDemagTensor\TileDemagTensor\x64\Release\ -lTileDemagTensor ...
       -Isource\TileDemagTensor\TileDemagTensor\x64\Release\ ...        
       '-Lc:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2019\windows\mkl\lib\intel64_win\' -lmkl_intel_lp64 ...          
    source\MagTenseMEX\MagTenseMEX\IterateMagnetization_mex.f90 COMPFLAGS="$COMPFLAGS /O3 /extend_source:132 /real_size:64 /fpe:0" -R2018a

movefile IterateMagnetization_mex.mexw64 matlab\MEX_files\IterateMagnetization_mex.mexw64
movefile IterateMagnetization_mex.mexw64.pdb matlab\MEX_files\IterateMagnetization_mex.mexw64.pdb
        
mex -g -Lsource\DemagField\DemagField\x64\Release\ -lDemagField...
       -Isource\DemagField\DemagField\x64\Release\ ...
       -Lsource\NumericalIntegration\NumericalIntegration\x64\Release\ -lNumericalIntegration ...
       -Isource\NumericalIntegration\NumericalIntegration\x64\Release\ ...
       -Lsource\TileDemagTensor\TileDemagTensor\x64\Release\ -lTileDemagTensor ...
       -Isource\TileDemagTensor\TileDemagTensor\x64\Release\ ...        
       '-Lc:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2019\windows\mkl\lib\intel64_win\' -lmkl_intel_lp64 ...          
    source\MagTenseMEX\MagTenseMEX\getHFromTiles_mex.f90 COMPFLAGS="$COMPFLAGS /O3 /extend_source:132 /real_size:64  /fpe:0" -R2018a

movefile getHFromTiles_mex.mexw64 matlab\MEX_files\getHFromTiles_mex.mexw64
movefile getHFromTiles_mex.mexw64.pdb matlab\MEX_files\getHFromTiles_mex.mexw64.pdb

mex -g -Lsource\DemagField\DemagField\x64\Release\ -lDemagField...
       -Isource\DemagField\DemagField\x64\Release\ ...
       -Lsource\NumericalIntegration\NumericalIntegration\x64\Release\ -lNumericalIntegration ...
       -Isource\NumericalIntegration\NumericalIntegration\x64\Release\ ...
       -Lsource\TileDemagTensor\TileDemagTensor\x64\Release\ -lTileDemagTensor ...
       -Isource\TileDemagTensor\TileDemagTensor\x64\Release\ ...   
       '-Lc:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2019\windows\mkl\lib\intel64_win\' -lmkl_intel_lp64 ...                 
    source\MagTenseMEX\MagTenseMEX\getNFromTile_mex.f90 COMPFLAGS="$COMPFLAGS /O3 /extend_source:132 /real_size:64  /fpe:0" -R2018a

movefile getNFromTile_mex.mexw64 matlab\MEX_files\getNFromTile_mex.mexw64
movefile getNFromTile_mex.mexw64.pdb matlab\MEX_files\getNFromTile_mex.mexw64.pdb

mex -g -Lsource\MagneticForceIntegrator\MagneticForceIntegrator\x64\Release\ -lMagneticForceIntegrator...
       -Isource\MagneticForceIntegrator\MagneticForceIntegrator\x64\Release\ ...
       -Lsource\DemagField\DemagField\x64\Release\ -lDemagField...
       -Isource\DemagField\DemagField\x64\Release\ ...
       -Lsource\NumericalIntegration\NumericalIntegration\x64\Release\ -lNumericalIntegration ...
       -Isource\NumericalIntegration\NumericalIntegration\x64\Release\ ...
       -Lsource\TileDemagTensor\TileDemagTensor\x64\Release\ -lTileDemagTensor ...
       -Isource\TileDemagTensor\TileDemagTensor\x64\Release\ ...                
       '-Lc:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2019\windows\mkl\lib\intel64_win\' -lmkl_intel_lp64 ...          
    source\MagTenseMEX\MagTenseMEX\getMagForce_mex.f90 COMPFLAGS="$COMPFLAGS /O2 /Qopenmp /extend_source:132 /real_size:64  /fpe:0" -R2018a

movefile getMagForce_mex.mexw64 matlab\MEX_files\getMagForce_mex.mexw64
movefile getMagForce_mex.mexw64.pdb matlab\MEX_files\getMagForce_mex.mexw64.pdb
