close all
clear all
%COMPFLAGS5="$COMPFLAGS /MT /Qopenmp /extend_source:132 /real_size:64" ...
mex  -LNumericalIntegrationLib\NumericalIntegration\NumericalIntegration\x64\release\ -lNumericalIntegration ...
    -INumericalIntegrationLib\NumericalIntegration\NumericalIntegration\x64\release\ ...
    -LMagStatPrismLib\MagStatPrismLib\x64\release\ -lMagStatPrismLib ...
    -IMagStatPrismLib\MagStatPrismLib\x64\release\ ...
    MagStatPrismMEX\MagStatPrismMEX\integral2_mex.f90 COMPFLAGS="$COMPFLAGS  /Qopenmp /extend_source:132 /real_size:64 "
    