[build-system]
requires = ["setuptools>=61.0", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"magtense.lib" = ["*.pyd", "*.so", "*.dll"]
"magtense.mat" = ["*.csv"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
version = {attr = "magtense.__version__"}

[project]
name = "magtense"
authors = [
  { name="Stefan Pollok", email="spol@dtu.dk" },
]
description = "MagTense - a micromagnetism and magnetostatic framework"
dynamic = ["dependencies", "version"]
readme = "README_top.md"
requires-python = ">=3.12"
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
keywords = [
    "Micromagnetism",
    "Magnetostatics",
    "Demagnetization tensor",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering",
]

[project.urls]
"Homepage" = "https://www.magtense.org/"
"Source" = "https://github.com/cmt-dtu-energy/MagTense"
"Documentation" = "https://cmt-dtu-energy.github.io/MagTense/"

[tool.mypy]
python_version = "3.13"
warn_return_any = true
warn_unused_configs = true
warn_unused_ignores = true

[tool.ruff]
line-length = 88

# Lint and format Jupyter Notebooks.
extend-include = ["*.ipynb"]
extend-exclude = ["__pycache__", "data"]

[tool.ruff.lint]
select = [
  "E",   # pycodestyle
  "F",   # Pyflakes
  "I",   # isort
  "UP",  # pyupgrade
  "ANN", # flake8-annotations
  "B",   # flake8-bugbear
  "A",   # flake8-builtins
  "C4",  # flake8-comprehensions
  "EM",  # flake8-errmsg
  "ISC", # flake8-implicit-str-concat
  "ICN", # flake8-import-conventions
  "LOG", # flake8-logging
  "PIE", # flake8-pie
  "PT",  # flake8-pytest-style
  "RSE", # flake8-raise
  "SIM", # flake8-simplify
  "PTH", # flake8-use-pathlib
  "PL",   # pylint
  "TRY",  # tryceratops
  "FLY",  # flynt
  "NPY",  # Numpy-specific rules
  "PERF", # perflint
  "FURB", # refurb
  "RUF",  # ruff-specific rules
]
ignore = [
  # Ignore rules that conflict with the formatter:
  "ANN001", # missing type annotation
  "ANN002",
  "ANN003",
  "E111",
  "E114",
  "E117",
  "PLR0912", # Too many branches
  "PLR0913",
  "PLR0915",
  "PLR2004",
]
preview = true
explicit-preview-rules = true
extend-select = [
  "E402", # allow import violations for os.environ calls
]

# Allow fix for all enabled rules (when '--fix') is provided.
fixable = ["ALL"]
unfixable = []

# 4. Ignore `E402` (import violations) in all '__init__.py' files.
[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402"]

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true

[tool.ruff.lint.isort.sections]
# Put IPython into its own section.
"IPython" = ["IPython"]
