function [dfxdmx,dfydmx,dfzdmx,dfxdmy,dfydmy,dfzdmy,dfxdmz,dfydmz,dfzdmz,...
    dfxdmxdmx,dfydmxdmx,dfzdmxdmx,dfxdmxdmy,dfydmxdmy,dfzdmxdmy,dfxdmxdmz,dfydmxdmz,dfzdmxdmz,...
    dfxdmydmx,dfydmydmx,dfzdmydmx,dfxdmydmy,dfydmydmy,dfzdmydmy,dfxdmydmz,dfydmydmz,dfzdmydmz,...
    dfxdmzdmx,dfydmzdmx,dfzdmzdmx,dfxdmzdmy,dfydmzdmy,dfzdmzdmy,dfxdmzdmz,dfydmzdmz,dfzdmzdmz] = FirstAndSecondDerivativeOfFcomponents(mx,my,mz)
%SECONDDERIVATIVEOFF01
%    H = SECONDDERIVATIVEOFF01(MX,MY,MZ)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    24-May-2019 11:50:35
%    symbolicTestEvolution03new.m

t2 = my.^2;
t3 = mz.^2;
t4 = mx.^2;

t5 = t2+t3+t4;

t6 = 1.0./t5.^(5.0./2.0);

t8 = t4.*2.0;
t7 = t2+t3-t8;
t9 = mx.*my.*mz.*t6.*3.0;
t11 = t2.*2.0;
t10 = t3+t4-t11;
t13 = t3.*2.0;
t12 = t2+t4-t13;

t6b = 1.0./t5.^(3.0./2.0);
t7b = 1.0./sqrt(t5);

dfxdmx = t7b-t4.*t6b ;
dfydmx = -mx.*my.*t6b ;
dfzdmx = -mx.*mz.*t6b ;
dfxdmy = -mx.*my.*t6b ;
dfydmy = t7b-t2.*t6b ;
dfzdmy = -my.*mz.*t6b ;
dfxdmz = -mx.*mz.*t6b ;
dfydmz = -my.*mz.*t6b ;
dfzdmz = t7b-t3.*t6b ;


dfxdmxdmx = mx.*t6.*(t2+t3).*-3.0 ; 
dfydmxdmx = -my.*t6.*t7 ; 
dfzdmxdmx = -mz.*t6.*t7 ; 
dfxdmxdmy = -my.*t6.*t7 ; 
dfydmxdmy = -mx.*t6.*t10 ; 
dfzdmxdmy = t9 ; 
dfxdmxdmz = -mz.*t6.*t7 ; 
dfydmxdmz = t9 ; 
dfzdmxdmz = -mx.*t6.*t12 ; 

dfxdmydmx = -my.*t6.*t7 ; 
dfydmydmx = -mx.*t6.*t10 ; 
dfzdmydmx = t9 ; 
dfxdmydmy = -mx.*t6.*t10 ; 
dfydmydmy = my.*t6.*(t3+t4).*-3.0 ; 
dfzdmydmy = -mz.*t6.*t10 ; 
dfxdmydmz = t9 ; 
dfydmydmz = -mz.*t6.*t10 ; 
dfzdmydmz = -my.*t6.*t12 ; 

dfxdmzdmx =-mz.*t6.*t7 ; 
dfydmzdmx = t9 ; 
dfzdmzdmx = -mx.*t6.*t12 ; 
dfxdmzdmy = t9 ; 
dfydmzdmy = -mz.*t6.*t10 ; 
dfzdmzdmy = -my.*t6.*t12 ; 
dfxdmzdmz = -mx.*t6.*t12 ; 
dfydmzdmz = -my.*t6.*t12 ; 
dfzdmzdmz = mz.*t6.*(t2+t4).*-3.0;
