name: cvode - Build and test with win/intel/ninja

on: push

jobs:
  build_and_test:
    runs-on: windows-latest

    steps:
    - uses: fortran-lang/setup-fortran@v1
      id: setup-fortran
      with:
        compiler: intel
        version: '2025.0'
    
    # - uses: Jimver/cuda-toolkit@v0.2.22
    #   id: cuda-toolkit
    #   with:
    #     cuda: '12.8.1'
    #     # sub-packages: '["nvcc", "cusparse", "cublas", "cudart", "nvjitlink"]'

    - name: Install Ninja
      run: choco install ninja

    - uses: actions/checkout@v4
      with:
        repository: LLNL/sundials
        ref: 'v7.2.1'

    - name: Configure CMake
      run: |
        mkdir ${{github.workspace}}/install
        cmake -G "Ninja" -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DBUILD_ARKODE=OFF -DBUILD_CVODES=ON -DBUILD_CVODES=OFF -DBUILD_IDA=OFF -DBUILD_IDAS=OFF -DBUILD_KINSOL=OFF -DBUILD_SHARED_LIBS=ON -DBUILD_STATIC_LIBS=OFF -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install -DEXAMPLES_INSTALL_PATH=${{github.workspace}}/install/examples -DCMAKE_C_FLAGS=-Wno-deprecated-declarations -DCMAKE_C_COMPILER=icx-cl -DCMAKE_CXX_COMPILER=icx-cl -DCMAKE_Fortran_COMPILER=ifx -DBUILD_FORTRAN_MODULE_INTERFACE=ON -DENABLE_OPENMP=ON -DENABLE_ONEMKL=ON -DONEMKL_DIR='${{ env.ONEAPI_ROOT }}'
    
    - name: Build
      run: cmake --build ${{github.workspace}}/build --verbose

    - name: Install
      run: cmake --install ${{github.workspace}}/build --verbose

    - name: Check installation
      shell: bash -el {0}
      run: |
        ls -al '${{github.workspace}}'/install
        ls -al '${{github.workspace}}'/install/lib
