name: customized-win-shells

on: [push]

jobs:
  customized-win-shells:
    strategy:
      matrix:
        CVODE-compile: [CVODE,noCVODE]
        CUDA-compile: [CUDA,noCUDA]
    runs-on: windows-latest

    steps:
    - name: Test
      env:
        CUDA: ${{ matrix.CUDA-compile == 'noCUDA' && '0' || '1' }}
        CVODE: ${{ matrix.CVODE-compile == 'noCVODE' && '0' || '1' }}
      shell: pwsh -NoExit -ExecutionPolicy ByPass -File {0}
      run: |
        cd ${{ github.workspace }}
        pwd
        $env:CUDA 
        $env:CVODE
        
    - name: Dir
      shell: cmd /C CALL {0}
      run: |
        dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC"

    - name: Dir
      shell: cmd /C CALL {0}
      run: >-
        dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools"

    - name: Dir
      shell: cmd /C CALL {0}
      run: >-
        dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC"

    - name: Dir
      shell: cmd /C CALL {0}
      run: >-
        dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.43.34808"

    - name: Dir
      shell: cmd /C CALL {0}
      run: >-
        dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.43.34808\bin"
    
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: magtense-env
        miniforge-version: latest
        channels: conda-forge,nvidia/label/cuda-12.6.3,https://software.repos.intel.com/python/conda/
        auto-activate-base: false

    - name: Install minimal packages in bash
      shell: bash -el {0}
      run: |
        conda install cuda-nvcc libcusparse-dev libcublas-dev cuda-cudart-dev make vs2022_win-64 "dpcpp_win-64"

    - name: Dir
      shell: bash -el {0}
      working-directory: ${{ github.workspace }}/source/MagTenseFortranCuda/cuda
      run: |
        ls -lh "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.43.34808\bin\Hostx64\x64"

    - name: Run Command Prompt
      shell: bash -el {0}
      working-directory: ${{ github.workspace }}/source/MagTenseFortranCuda/cuda
      run: |
        nvcc -c MagTenseCudaBlas.cu -ccbin "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.43.34808\bin\Hostx64\x64" -o MagTenseCudaBlas.o

    - name: Run Developer PowerShell for VS 2022
      shell: pwsh -NoExit -ExecutionPolicy ByPass -File {0}
      run: |
        cd "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\"
        .\Launch-VsDevShell.ps1
        cd ${{ github.workspace }}/source/MagTenseFortranCuda/cuda
        make wrap
        ls

    - name: Run x64 Native Tools Command Prompt for VS 2022
      shell: cmd /k "{0}" -arch=amd64 -host_arch=x64
      working-directory: ${{ github.workspace }}/source/MagTenseFortranCuda/cuda
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat"
        nvcc && make cuda
