name: Building and testing Matlab MEX files on Windows and Linux

on: [push, workflow_dispatch]

jobs:
  build-windows:
    runs-on: [windows-latest]
    env:
      build_file: python/.build/environment_win.yml
    steps:
      - uses: actions/checkout@v4
   
      - name: Setup Miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          activate-environment: magtense-env
          environment-file: ${{ env.build_file }}
          use-mamba: true

      #- name: Setup Miniforge
      #  uses: conda-incubator/setup-miniconda@v3
      #  with:
      #    miniforge-version: latest
      #    activate-environment: magtense-env
      #    use-mamba: true

      #- name: Cache conda
      #  uses: actions/cache@v4
      #  env:
      #    # Increase this value to reset cache manually
      #    cache_number: 0
      #  with:
      #    path: ${{ env.CONDA }}\envs
      #    key: conda-${{ runner.os }}-${{ hashFiles(env.build_file) }}-${{ env.cache_number }}
      #  id: cache

      #- name: Update environment if needed
      #  run: conda env update -n magtense-env -f ${{ env.build_file }}
      #  if: steps.cache.outputs.cache-hit != 'true'

      - name: Set up MATLAB R2024b
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2024b
          
      - name: Build MagTense .o-files without CUDA using Developer PowerShell for VS 2022
        shell: pwsh -NoExit -ExecutionPolicy ByPass -File {0}
        run: |
          cd "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\"
          .\Launch-VsDevShell.ps1
          conda info
          cd ${{ github.workspace }}
          pwd
          make magnetostatic micromagnetism forceintegrator USE_CUDA=0 USE_CVODE=0 USE_MATLAB=1 MATLAB_INCLUDE=D:/hostedtoolcache/windows/MATLAB/2024.2.999/x64/extern/include
            
      - name: Setup a symbolic link to the ifx compiler so that Matlab's "mex -setup FORTRAN" can find it
        shell: powershell
        run: |
          cd C:\Users\runneradmin\miniconda3\envs\magtense-env\Library 
          mkdir compiler 
          cd C:\Users\runneradmin\miniconda3\envs\magtense-env\Library\compiler
          mkdir 2024.2 
          cd 2024.2 
          cmd /c mklink /D bin C:\Users\runneradmin\miniconda3\envs\magtense-env\Library\bin 
          
      #- name: Check that the symbolic link has been created
      #  shell: cmd /C CALL {0}
      #  run: >-
      #    dir C:\Users\runneradmin\miniconda3\envs\magtense-env\Library\compiler\2024.2
      
      - name: Compile MEX code using Matlab without CUDA and test
        uses: matlab-actions/run-command@v2
        with:
          command: setenv('ONEAPI_ROOT',"C:\Users\runneradmin\miniconda3\envs\magtense-env\Library"); mex -setup FORTRAN; cd('D:/a/MagTense/MagTense/matlab'); pwd; dir; buildMagTenseMEX('USE_CUDA',false,'USE_CVODE',false,'mkl_include','C:\Users\runneradmin\miniconda3\envs\magtense-env\opt\compiler\include\intel64','mkl_lib','C:\Users\runneradmin\miniconda3\envs\magtense-env\Library\lib','mkl_lp64','C:\Users\runneradmin\miniconda3\envs\magtense-env\Library\include\intel64\lp64'); cd('examples/Micromagnetism/mumag_micromag_Std_problem_4'); [~,~,~,~,~,~,int_error] = Standard_problem_4('USE_CUDA',false); disp(int_error);
          
      - name: Use nvcc to build the CUDA file
        shell: bash -el {0}
        working-directory: ${{ github.workspace }}/source/MagTenseFortranCuda/cuda
        run: |
          nvcc -c MagTenseCudaBlas.cu -ccbin "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.43.34808\bin\Hostx64\x64" -o MagTenseCudaBlas.o

      - name: Make the wrapper for the CUDA file using icx in a Developer PowerShell for VS 2022
        shell: pwsh -NoExit -ExecutionPolicy ByPass -File {0}
        run: |
          cd "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\"
          .\Launch-VsDevShell.ps1
          cd ${{ github.workspace }}/source/MagTenseFortranCuda/cuda
          make wrap
          ls
      
      - name: Build MagTense .o-files with CUDA using Developer PowerShell for VS 2022 (and make clean also)
        shell: pwsh -NoExit -ExecutionPolicy ByPass -File {0}
        run: |
          cd "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\"
          .\Launch-VsDevShell.ps1
          conda info
          cd ${{ github.workspace }}
          pwd
          make clean
          make magnetostatic micromagnetism forceintegrator USE_CUDA=1 USE_CVODE=0 USE_MATLAB=1 MATLAB_INCLUDE=D:/hostedtoolcache/windows/MATLAB/2024.2.999/x64/extern/include
      
      - name: Compile MEX code using Matlab with CUDA and test
        uses: matlab-actions/run-command@v2
        with:
          command: setenv('ONEAPI_ROOT',"C:\Users\runneradmin\miniconda3\envs\magtense-env\Library"); mex -setup FORTRAN; cd('D:/a/MagTense/MagTense/matlab'); pwd; dir; buildMagTenseMEX('USE_CUDA',true,'USE_CVODE',false,'mkl_include','C:\Users\runneradmin\miniconda3\envs\magtense-env\opt\compiler\include\intel64','mkl_lib','C:\Users\runneradmin\miniconda3\envs\magtense-env\Library\lib','mkl_lp64','C:\Users\runneradmin\miniconda3\envs\magtense-env\Library\include\intel64\lp64');
       
      - name: Check created MEX-files
        shell: bash -el {0}
        run: |
          dir D:/a/MagTense/MagTense/matlab/MEX_files
        
      - name: Archive MEX-files
        uses: actions/upload-artifact@v4
        with:
          name: MEX-Windows
          path: D:/a/MagTense/MagTense/matlab/MEX_files/*

###

  test-windows:
    strategy:
      matrix:
        mat-version: [R2020b,R2024b]
    runs-on: [self-hosted,Windows,CUDA]
    needs: build-windows
    defaults:
      run:
        shell: bash -el {0}
    
    steps:
    - name: Checkout test scripts
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          matlab
          documentation
    
    - name: Download the MEX files as an artifact
      uses: actions/download-artifact@v4
      with:
        name: MEX-Windows
        path: ${{ github.workspace }}/matlab/MEX_files
        
    - name: Check that the MEX-files are there
      shell: cmd /C CALL {0}
      run: |
        dir ${{ github.workspace }}\matlab\MEX_files
    
    - name: Run MATLAB R2023a
      if: ${{ matrix.mat-version == 'R2023a' }}
      shell: cmd /C CALL {0}
      run: |
        "C:\Program Files\MATLAB\R2023a\bin\matlab.exe" -batch "cd('C:\actions-runner\_work\MagTense\MagTense\matlab\examples\Micromagnetism\mumag_micromag_Std_problem_4'); [~,~,~,~,~,~,int_error] = Standard_problem_4('USE_CUDA',true)"
        
    - name: Run MATLAB R2023b
      if: ${{ matrix.mat-version == 'R2023b' }}
      shell: cmd /C CALL {0}
      run: |
        "C:\Program Files\MATLAB\R2023b\bin\matlab.exe" -batch "cd('C:\actions-runner\_work\MagTense\MagTense\matlab\examples\Micromagnetism\mumag_micromag_Std_problem_4'); [~,~,~,~,~,~,int_error] = Standard_problem_4('USE_CUDA',true)"
        
    - name: Run MATLAB R2024a
      if: ${{ matrix.mat-version == 'R2024a' }}
      shell: cmd /C CALL {0}
      run: |
        "C:\Program Files\MATLAB\R2024a\bin\matlab.exe" -batch "cd('C:\actions-runner\_work\MagTense\MagTense\matlab\examples\Micromagnetism\mumag_micromag_Std_problem_4'); [~,~,~,~,~,~,int_error] = Standard_problem_4('USE_CUDA',true)"
        
    - name: Run MATLAB R2024b
      if: ${{ matrix.mat-version == 'R2024b' }}
      shell: cmd /C CALL {0}
      run: |
        "C:\Program Files\MATLAB\R2024b\bin\matlab.exe" -batch "cd('C:\actions-runner\_work\MagTense\MagTense\matlab\examples\Micromagnetism\mumag_micromag_Std_problem_4'); [~,~,~,~,~,~,int_error] = Standard_problem_4('USE_CUDA',true)"
  
  
  #################################
  
  build-linux:
    strategy:
      matrix:
        py-version: [312]
        mat-version: [R2024a]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    env:
      build_file: python/.build/env-${{ matrix.py-version}}-linux.yml

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Miniforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        activate-environment: magtense-env
        use-mamba: true

    - name: Cache conda
      uses: actions/cache@v4
      env:
        # Increase this value to reset cache manually
        cache_number: 0
      with:
        path: ${{ env.CONDA }}/envs
        key: conda-${{ runner.os }}-${{ hashFiles(env.build_file) }}-${{ env.cache_number }}
      id: cache

    - name: Update environment if needed
      run: conda env update -n magtense-env -f ${{ env.build_file }}
      if: steps.cache.outputs.cache-hit != 'true'

    - name: Set up MATLAB R2024a
      if: ${{ matrix.mat-version == 'R2024a' }}
      uses: matlab-actions/setup-matlab@v2
      with:
        release: R2024a

    - name: Set up MATLAB R2024b
      if: ${{ matrix.mat-version == 'R2024b' }}
      uses: matlab-actions/setup-matlab@v2
      with:
        release: R2024b    

    - name: Compile Fortran source code with CUDA including R2024a
      if: ${{ matrix.mat-version == 'R2024a' }}
      working-directory: ${{ github.workspace }}
      run: make magnetostatic micromagnetism cuda forceintegrator USE_CUDA=1 USE_CVODE=0 USE_MATLAB=1 MATLAB_INCLUDE=/opt/hostedtoolcache/MATLAB/2024.1.999/x64/extern/include

    - name: Compile Fortran source code with CUDA including R2024b
      if: ${{ matrix.mat-version == 'R2024b' }}
      working-directory: ${{ github.workspace }}
      run: make magnetostatic micromagnetism cuda forceintegrator USE_CUDA=1 USE_CVODE=0 USE_MATLAB=1 MATLAB_INCLUDE=/opt/hostedtoolcache/MATLAB/2024.2.999/x64/extern/include 

    - name: Compile MEX code using Matlab with CUDA
      uses: matlab-actions/run-command@v2
      with:
        command: cd('matlab'); buildMagTenseMEX('USE_RELEASE', true, 'USE_CUDA', true, 'USE_CVODE', false);

    - name: Clean up the source files
      working-directory: ${{ github.workspace }}
      run: make clean

    - name: Compile Fortran source code without CUDA using R2024a
      if: ${{ matrix.mat-version == 'R2024a' }}
      working-directory: ${{ github.workspace }}
      run: make magnetostatic micromagnetism cuda forceintegrator USE_CUDA=0 USE_CVODE=0 USE_MATLAB=1 MATLAB_INCLUDE=/opt/hostedtoolcache/MATLAB/2024.1.999/x64/extern/include

    - name: Compile Fortran source code without CUDA using R2024b
      if: ${{ matrix.mat-version == 'R2024b' }}
      working-directory: ${{ github.workspace }}
      run: make magnetostatic micromagnetism cuda forceintegrator USE_CUDA=0 USE_CVODE=0 USE_MATLAB=1 MATLAB_INCLUDE=/opt/hostedtoolcache/MATLAB/2024.2.999/x64/extern/include

    - name: Compile MEX code using Matlab without CUDA and test
      uses: matlab-actions/run-command@v2
      with:
        command: cd('matlab'); buildMagTenseMEX('USE_RELEASE', true, 'USE_CUDA', false, 'USE_CVODE', false); cd('examples/Micromagnetism/mumag_micromag_Std_problem_4'); [~,~,~,~,~,~,int_error] = Standard_problem_4('USE_CUDA',false); disp(int_error);

    - name: Archive MEX-files
      uses: actions/upload-artifact@v4
      with:
        name: MEX-Linux
        path: ${{ github.workspace }}/matlab/MEX_files/*

###
    
  test-linux:
    strategy:
      matrix:
        mt-punit: [cpu]
        mat-version: [R2024a]
        os-version: [ubuntu-latest]
        exclude:
          - os-version: ubuntu-latest
            mat-version: 'R2022b'
    runs-on: ${{matrix.os-version}}
    needs: build-linux
    defaults:
      run:
        shell: bash -el {0}
    
    steps:
    - name: Checkout test scripts
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          matlab
          documentation
      
    - name: Download the MEX files as an artifact
      uses: actions/download-artifact@v4
      with:
        name: MEX-Linux
        path: ${{ github.workspace }}/matlab/MEX_files

    - name: Set up MATLAB R2022b
      if: ${{ matrix.mat-version == 'R2022b' }}
      uses: matlab-actions/setup-matlab@v2
      with:
        release: R2022b

    - name: Set up MATLAB R2024a
      if: ${{ matrix.mat-version == 'R2024a' }}
      uses: matlab-actions/setup-matlab@v2
      with:
        release: R2024a

    - name: Set up MATLAB R2024b
      if: ${{ matrix.mat-version == 'R2024b' }}
      uses: matlab-actions/setup-matlab@v2
      with:
        release: R2024b

    - name: Run test script on download MEX-file without CUDA
      uses: matlab-actions/run-command@v2
      with:
        command: cd('matlab/examples/Micromagnetism/mumag_micromag_Std_problem_4'); [~,~,~,~,~,~,int_error] = Standard_problem_4('USE_CUDA',false); disp(int_error);
