name: Python pip-wheel with conda build and test on Windows and Linux

on:
  pull_request:
    branches:
      - master
  workflow_call:
    inputs:
      tag:
        required: false
        type: string
  workflow_dispatch:

jobs:
  build-wheel:
    strategy:
      matrix:
        py-version: [312, 313]
        cvode: [1]
        sys:
          - { os: windows-latest, name: win, whl-arch: win_amd64}
          - { os: ubuntu-latest, name: linux, whl-arch: manylinux1_x86_64 }
    runs-on: ${{ matrix.sys.os }}
    # Workaround: Issue with msvc-dev-cmd and new conda installation
    needs: [cache-conda-win, build-cvode]
    defaults:
      run:
        shell: bash -el {0}
    env:
      build_file: python/.build/env-${{ matrix.py-version }}-${{ matrix.sys.name }}.yml

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Fetch tags
      if: "${{ inputs.tag == '' }}"
      run: git fetch --tags origin

    - name: Get latest release tag
      id: previoustag
      if: "${{ inputs.tag == '' }}"
      uses: WyriHaximus/github-action-get-previous-tag@v1
      with:
        fallback: 1.0.0

    - name: Setup msvc-dev-cmd
      if: ${{ runner.os == 'Windows' }}
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64

    - name: Setup Miniforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        activate-environment: magtense-env
        use-mamba: true

    - name: Cache conda
      uses: actions/cache@v4
      env:
        cache_number: 0
      with:
        path: ${{ env.CONDA }}/envs
        key: conda-${{ runner.os }}-${{ hashFiles(env.build_file) }}-${{ env.cache_number }}
      id: cache

    - name: Update environment
      run: conda env update -f ${{ env.build_file }}
      if: steps.cache.outputs.cache-hit != 'true'

    - name: Download cvode (sundials-7.2.1)
      if: ${{ matrix.cvode == 1 }}
      uses: actions/download-artifact@v4
      with:
        name: cvode-${{ runner.os }}
        path: ${{ github.workspace }}/cvode/
    
    - name: Create directory for wrappers of compiled Fortran source code
      run: |
        mkdir '${{ github.workspace }}'/python/cpu_libs
        mkdir '${{ github.workspace }}'/python/cu12_libs
    
    # Workaround: Issue with msvc-dev-cmd and link.exe in the conda environment
    - name: Win - Delete link.exe
      if: ${{ runner.os == 'Windows' }}
      run: rm '${{ env.CONDA }}'/envs/magtense-env/Library/usr/bin/link.exe
    
    # Shell cannot use job/matrix templates: https://github.com/actions/runner/issues/444
    - name: Win - Compile Fortran source code and build Python wrapper
      if: ${{ runner.os == 'Windows' }}
      shell: pwsh -NoExit -ExecutionPolicy ByPass -File {0}
      working-directory: ${{ github.workspace }}
      run: |
        make python USE_CUDA=0 USE_CVODE=${{ matrix.cvode }} USE_MATLAB=0
        cp magtensesource.* ${{ github.workspace }}/python/cpu_libs/
        make clean
        make python USE_CUDA=1 USE_CVODE=${{ matrix.cvode }} USE_MATLAB=0
        cp magtensesource.* ${{ github.workspace }}/python/cu12_libs/
        make clean
    
    - name: Linux - Compile Fortran source code and build Python wrapper
      if: ${{ runner.os == 'Linux' }}
      working-directory: ${{ github.workspace }}
      run: |
        make python USE_CUDA=0 USE_CVODE=${{ matrix.cvode }} USE_MATLAB=0
        cp magtensesource.* '${{ github.workspace }}'/python/cpu_libs/
        make clean
        make python USE_CUDA=1 USE_CVODE=${{ matrix.cvode }} USE_MATLAB=0
        cp magtensesource.* '${{ github.workspace }}'/python/cu12_libs/
        make clean

    - name: Build pip-wheels
      if: "${{ inputs.tag == '' }}"
      working-directory: ${{ github.workspace }}/python/
      run: |
        sed -i 's/1.0.0/${{ steps.previoustag.outputs.tag }}/' src/magtense/__init__.py
        python -m pip install build
        python .build/dist_pypi.py --py_version ${{ matrix.py-version }} --platform ${{ matrix.sys.name }} --pkg_version ${{ steps.previoustag.outputs.tag }}

    - name: Deployment - Build pip-wheels
      if: "${{ inputs.tag != '' }}"
      working-directory: ${{ github.workspace }}/python/
      run: |
        sed -i 's/1.0.0/${{ inputs.tag }}/' src/magtense/__init__.py
        python .build/dist_pypi.py --py_version ${{ matrix.py-version }} --platform ${{ matrix.sys.name }} --pkg_version ${{ inputs.tag }}

    - name: cpu - Archive pip-wheel
      uses: actions/upload-artifact@v4
      with:
        name: pip-wheel-py${{ matrix.py-version }}-cpu-${{ runner.os }}
        path: ${{ github.workspace }}/python/dist/magtense-*-0-py${{ matrix.py-version }}-none-${{ matrix.sys.whl-arch }}.whl

    - name: cu12 - Archive pip-wheel
      uses: actions/upload-artifact@v4
      with:
        name: pip-wheel-py${{ matrix.py-version }}-cu12-${{ runner.os }}
        path: ${{ github.workspace }}/python/dist/magtense-*-1-py${{ matrix.py-version }}-none-${{ matrix.sys.whl-arch }}.whl


  test-wheel:
    strategy:
      matrix:
        mt-punit: [cpu, cu12]
        py-version:
          - { name: 312, id: "3.12" }
          - { name: 313, id: "3.13" }
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    needs: build-wheel
    defaults:
      run:
        shell: bash -el {0}
    
    steps:
    - name: Checkout test scripts
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          python/tests/
          documentation/examples_FEM_validation/
    
    - name: Download a single artifact
      uses: actions/download-artifact@v4
      with:
        name: pip-wheel-py${{ matrix.py-version.name }}-${{ matrix.mt-punit }}-${{ runner.os }}

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.py-version.id }}

    - name: Install pip-wheel and pytest
      run: |
        python3 -m pip install '${{ github.workspace }}'/*.whl
        python3 -m pip install pytest
        pytest

        
  cache-conda-win:
    strategy:
      matrix:
        py-version: [312, 313]
    runs-on: windows-latest
    env:
      build_file: python/.build/env-${{ matrix.py-version }}-win.yml

    steps:
    - name: Checkout environment file
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          python/.build/

    - name: Setup Miniforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        activate-environment: magtense-env
        use-mamba: true

    - name: Cache conda
      uses: actions/cache@v4
      env:
        cache_number: 0
      with:
        path: ${{ env.CONDA }}/envs
        key: conda-${{ runner.os }}-${{ hashFiles(env.build_file) }}-${{ env.cache_number }}
      id: cache

    - name: Update environment
      run: conda env update -f ${{ env.build_file }}
      if: steps.cache.outputs.cache-hit != 'true'

  
  build-cvode:
    name: cvode
    uses: ./.github/workflows/cmake-sundials-cvode.yml
