name: Python pip-wheel via make python-interface (Linux, CUDA)

on:
  pull_request:
    branches:
      - master
  workflow_call:
    inputs:
      tag:
        required: false
        type: string
  push:
    branches:
      - fabio
  workflow_dispatch:

jobs:
  build-wheel:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Fetch tags
      if: "${{ inputs.tag == '' }}"
      run: git fetch --tags origin

    - name: Get latest release tag
      id: previoustag
      if: "${{ inputs.tag == '' }}"
      uses: WyriHaximus/github-action-get-previous-tag@v1
      with:
        fallback: 1.0.0

    - name: Build Python interface via make python-interface
      working-directory: ${{ github.workspace }}
      run: make python-interface

    - name: Stage CUDA .so for dist_pypi.py
      working-directory: ${{ github.workspace }}
      run: |
        mkdir -p python/cu12_libs
        cp python/src/magtense/lib/magtensesource*.so python/cu12_libs/

    - name: Build pip-wheel
      if: "${{ inputs.tag == '' }}"
      working-directory: ${{ github.workspace }}/python/
      run: |
        sed -i 's/1.0.0/${{ steps.previoustag.outputs.tag }}/' src/magtense/__init__.py
        $HOME/miniconda3/bin/conda run -n magtense-env -- \
          python .build/dist_pypi.py \
            --py_version 314 --cu_version cu12 --platform linux \
            --pkg_version ${{ steps.previoustag.outputs.tag }}

    - name: Deployment - Build pip-wheel
      if: "${{ inputs.tag != '' }}"
      working-directory: ${{ github.workspace }}/python/
      run: |
        sed -i 's/1.0.0/${{ inputs.tag }}/' src/magtense/__init__.py
        $HOME/miniconda3/bin/conda run -n magtense-env -- \
          python .build/dist_pypi.py \
            --py_version 314 --cu_version cu12 --platform linux \
            --pkg_version ${{ inputs.tag }}

    - name: Archive pip-wheel
      uses: actions/upload-artifact@v4
      with:
        name: pip-wheel-py314-cu12-Linux
        path: ${{ github.workspace }}/python/dist/magtense-*-1-py314-none-manylinux1_x86_64.whl


  test-wheel:
    runs-on: ubuntu-latest
    needs: build-wheel
    defaults:
      run:
        shell: bash -el {0}

    steps:
    - name: Checkout test scripts
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          python/tests/
          documentation/examples_FEM_validation/

    - name: Download wheel artifact
      uses: actions/download-artifact@v4
      with:
        name: pip-wheel-py314-cu12-Linux

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: "3.14"

    - name: Install pip-wheel and run pytest
      run: |
        python3 -m pip install ${{ github.workspace }}/magtense-*-1-py314-none-manylinux1_x86_64.whl
        python3 -m pip install pytest
        pytest
