name: Testing windows runner

on: [push]

jobs:
  test-windows:
    strategy:
      matrix:
        mat-version: [R2023a,R2023b,R2024a,R2024b]
        cuda-version: [CUDA,noCUDA]
    runs-on: [ self-hosted, Windows, "${{ matrix.cuda-version }}"]
    defaults:
      run:
        shell: bash -el {0}
    
    steps:
    - name: Define with or without CUDA
      if: ${{ matrix.cuda-version == 'CUDA' }}
      env:
        CUDA: ${{ (contains(${{ matrix.cuda-version }}, 'noCUDA') && 'false') || 'true' }}
      shell: cmd /C CALL {0}
      run: |
        "C:\Program Files\MATLAB\${{ matrix.mat-version}}\bin\matlab.exe" -batch "disp(1+1); getenv('CUDA')"
    
    
    #- name: Define with or without CUDA        
    #  if: ${{ matrix.cuda-version == 'noCUDA' }}
    #  env:
    #    CUDA: false
    #  shell: cmd /C CALL {0}
    #  run: |
    #    "C:\Program Files\MATLAB\${{ matrix.mat-version}}\bin\matlab.exe" -batch "disp(1+1); sjask = getenv('CUDA')"
        
    #- name: Checkout test scripts
    #  uses: actions/checkout@v4
    #  with:
    #    sparse-checkout: |
    #      matlab
    #      documentation
    
    #- name: Dir
    #  shell: cmd /C CALL {0}
    #  run: |
    #    dir ${{ github.workspace }}\matlab\MEX_files
        
    #- name: Dir
    #  shell: cmd /C CALL {0}
    #  run: |
    #    "C:\Program Files\MATLAB\${{ matrix.mat-version}}\bin\matlab.exe" -batch cd('C:\actions-runner\_work\MagTense\MagTense\matlab\examples\Micromagnetism\mumag_micromag_Std_problem_4'); [~,~,~,~,~,~,int_error] = Standard_problem_4('USE_CUDA',true)"
       
   
   