name: Testing windows runner

on: [push]

jobs:
  test-windows:
    runs-on: [self-hosted,Windows,CUDA]
    defaults:
      run:
        shell: bash -el {0}
    
    steps:
    - name: Dir
      shell: cmd /C CALL {0}
      run: |
        "C:\Program Files\MATLAB\R2024b\bin\matlab.exe" -batch "C:\Users\github_runner\Downloads\MagTense-static-linking-mex\matlab\examples\Micromagnetism\mumag_micromag_Std_problem_4\Standard_problem_4('USE_CUDA',true)"
    
    - name: Checkout test scripts
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          matlab
          documentation
          
    #- name: Download the MEX files as an artifact
    #  uses: actions/download-artifact@v4
    #  with:
    #    name: MEX-Windows
    #    path: ${{ github.workspace }}/matlab/MEX_files




    - name: Run test script on download MEX-file with CUDA
      uses: matlab-actions/run-command@v2
      with:
        command: disp(2+2); pwd; dir
    
    #- name: Cmd.exe
    #    shell: cmd /C CALL {0}
    #    run: >-
    #      "C:\Program Files\MATLAB\R2024b\bin\matlab.exe" -batch "C:\Users\github_runner\Downloads\MagTense-static-linking-mex\matlab\examples\Micromagnetism\mumag_micromag_Std_problem_4\Standard_problem_4('USE_CUDA',true)"
    
    - name: Run test script on download MEX-file with CUDA
      uses: matlab-actions/run-command@v2
      with:
        command: cd('matlab/examples/Micromagnetism/mumag_micromag_Std_problem_4'); [~,~,~,~,~,~,int_error] = Standard_problem_4('USE_CUDA',true); disp(int_error);
    
