name: Win - Python package using conda / pip

on: [push]

jobs:
  build-win:
    strategy:
      matrix:
        py-version: [312]
    runs-on: [windows-latest]
    env:
      build_file: python/.build/environment_win.yml

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Miniforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        activate-environment: magtense-env
        use-mamba: true

    - name: Cache conda
      uses: actions/cache@v4
      env:
        # Increase this value to reset cache manually
        cache_number: 0
      with:
        path: ${{ env.CONDA }}/envs
        key: conda-${{ runner.os }}-${{ hashFiles(env.build_file) }}-${{ env.cache_number }}
      id: cache

    - name: Update environment
      run: conda env update -n magtense-env -f ${{ env.build_file }}
      if: steps.cache.outputs.cache-hit != 'true'
    
    - name: Compile with nvcc in Bash
      shell: bash -el {0}
      working-directory: ${{ github.workspace }}/source/MagTenseFortranCuda/cuda
      run: |
        nvcc -c MagTenseCudaBlas.cu -ccbin "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.43.34808\bin\Hostx64\x64" -o MagTenseCudaBlas.o

    - name: Link Cuda wrapper in Developer PowerShell for VS 2022
      shell: pwsh -NoExit -ExecutionPolicy ByPass -File {0}
      run: |
        cd "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\"
        .\Launch-VsDevShell.ps1
        cd ${{ github.workspace }}/source/MagTenseFortranCuda/cuda
        make wrap

    - name: Compile Fortran files in Developer PowerShell for VS 2022
      shell: pwsh -NoExit -ExecutionPolicy ByPass -File {0}
      run: |
        cd "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\"
        .\Launch-VsDevShell.ps1
        cd ${{ github.workspace }}
        make magnetostatic micromagnetism USE_CUDA=0 USE_CVODE=0 USE_MATLAB=0

    - name: Compile Fortran files in Developer PowerShell for VS 2022
      shell: pwsh -NoExit -ExecutionPolicy ByPass -File {0}
      run: |
        cd "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\"
        .\Launch-VsDevShell.ps1
        cd ${{ github.workspace }}
        make python-win USE_CUDA=0 USE_CVODE=0 USE_MATLAB=0

    - name: Build pip-wheels without cvode
      working-directory: ${{ github.workspace }}/python/
      run: python .build/dist_pypi.py --py_version ${{ matrix.py-version }} --cu_version cpu --platform win --no-cvode

    - name: cpu - Archive pip-wheel
      uses: actions/upload-artifact@v4
      with:
        name: pip-wheel-py${{ matrix.py-version }}-cpu
        path: ${{ github.workspace }}/python/dist/magtense-*-0-py${{ matrix.py-version }}-none-win_amd64.whl